//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customers
    {
        public decimal id { get; set; }
        public string short_name { get; set; }
        public string com_name { get; set; }
        public string com_addr { get; set; }
        public string contact_name { get; set; }
        public string contact_phone { get; set; }
        public string contract { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public string note { get; set; }
    }
}
